//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacion.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-G79D1BT\\SQLEXPRESS;Initial Catalog=Inventario_De_Productos;In" +
            "tegrated Security=True;TrustServerCertificate=True")]
        public string Inventario_De_ProductosConnectionString {
            get {
                return ((string)(this["Inventario_De_ProductosConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-G79D1BT\\SQLEXPRESS;Initial Catalog=Practica_De_Inventario_De_" +
            "Productos;Integrated Security=True;TrustServerCertificate=True")]
        public string Practica_De_Inventario_De_ProductosConnectionString {
            get {
                return ((string)(this["Practica_De_Inventario_De_ProductosConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-G79D1BT\\SQLEXPRESS;Initial Catalog=Practica_De_Inventario_De_" +
            "Productos2;Integrated Security=True;TrustServerCertificate=True")]
        public string Practica_De_Inventario_De_Productos2ConnectionString {
            get {
                return ((string)(this["Practica_De_Inventario_De_Productos2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-G79D1BT\\SQLEXPRESS;Initial Catalog=Sistema_de_venta2;Integrat" +
            "ed Security=True;TrustServerCertificate=True")]
        public string Sistema_de_venta2ConnectionString {
            get {
                return ((string)(this["Sistema_de_venta2ConnectionString"]));
            }
        }
    }
}
